services:
  go-app:
    image: go_image:3.0
    container_name: go-app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - back_net

  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: example  
    networks:
      - back_net


    
    
  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./nginx_certificates:/etc/nginx/certs
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

    depends_on:
      - go-app
    networks:
      - front_net
      - back_net
networks:
  back_net:
    internal: true

  front_net:
      
  