services:
  go-app:
    build: .
    container_name: go-app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: example  
    
    